// AUTO-GENERATED by Universal QA Agent
// App: process.env.APP_URL
// Generated: 2026-05-02T12:00:00Z
// Total scenarios: 11
// Safe mode: process.env.SAFE_MODE
// Destructive security tests: process.env.RUN_DESTRUCTIVE_SECURITY_TESTS

import { test, expect, Page } from '@playwright/test';
import { Selectors } from './selectors';

const APP_URL = process.env.APP_URL ?? 'http://localhost:4000';
const API_URL = process.env.API_URL ?? 'http://localhost:9000';

async function attachConsoleCapture(page: Page) {
  const errors: string[] = [];
  page.on('console', msg => {
    if (msg.type() === 'error') {
      // Ignore React fast refresh expected errors
      if (!msg.text().includes('Fast Refresh')) errors.push(msg.text());
    }
  });
  page.on('pageerror', err => {
    errors.push(err.message);
  });
  return {
    errors,
    assertNoErrors: () => expect(errors).toEqual([]),
  };
}

const XSS_PAYLOADS = [
  '<script>window.__xss=1</script>',
  '<img src=x onerror="window.__xss=1">',
];

const SQLI_PAYLOADS = [
  "' OR '1'='1",
  "'; DROP TABLE users; --",
];

test.describe('SEARCH', () => {
  test.describe('Happy Path', () => {
    test('SEARCH-HP-001 — Submit valid search query and navigate to results', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto('/');
      await Selectors.home.searchInput(page).fill('dune');
      await Selectors.home.searchButton(page).click();
      await expect(page).toHaveURL(/search\?q=dune/);
      consoleCapture.assertNoErrors();
    });

    test('SEARCH-HP-002 — Change country and submit search query', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto('/');
      await Selectors.home.searchInput(page).fill('dune');
      await Selectors.home.countrySelect(page).selectOption('GB');
      await Selectors.home.searchButton(page).click();
      await expect(page).toHaveURL(/search\?q=dune&country=GB/);
      consoleCapture.assertNoErrors();
    });

    test('SEARCH-HP-003 — Navigate back to home page from search results', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto('/search?q=dune&country=US');
      await Selectors.search.backLink(page).click();
      await expect(page).toHaveURL(APP_URL + '/');
      consoleCapture.assertNoErrors();
    });

    test('SEARCH-HP-004 — Click on a search result to view title detail', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto('/search?q=dune&country=US');
      await Selectors.search.titleCard(page).first().waitFor({ state: 'visible' });
      await Selectors.search.titleCard(page).first().click();
      await expect(page).toHaveURL(/title\/tmdb_movie_693134\?country=US/);
      consoleCapture.assertNoErrors();
    });
  });

  test.describe('Negative', () => {
    test('SEARCH-NEG-001 — Submit empty search query', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto('/');
      await Selectors.home.searchButton(page).click();
      // Should remain on the homepage
      await expect(page).toHaveURL(APP_URL + '/');
      consoleCapture.assertNoErrors();
    });
  });

  test.describe('Security', () => {
    for (const payload of XSS_PAYLOADS) {
      test(`SEARCH-SEC-001 — XSS payload: ${payload}`, async ({ page }) => {
        const consoleCapture = await attachConsoleCapture(page);
        await page.goto('/');
        await Selectors.home.searchInput(page).fill(payload);
        await Selectors.home.searchButton(page).click();
        const xssTriggered = await page.evaluate(() => (window as any).__xss);
        expect(xssTriggered).toBeUndefined();
        consoleCapture.assertNoErrors();
      });
    }

    for (const payload of SQLI_PAYLOADS) {
      test(`SEARCH-SEC-002 — SQLi payload: ${payload}`, async ({ page }) => {
        const consoleCapture = await attachConsoleCapture(page);
        await page.goto('/');
        await Selectors.home.searchInput(page).fill(payload);
        await Selectors.home.searchButton(page).click();
        await expect(page.locator('body')).not.toContainText(/SQL syntax|Exception/i);
        consoleCapture.assertNoErrors();
      });
    }
  });
});

test.describe('TITLE_DETAIL', () => {
  test.describe('Happy Path', () => {
    test('TITLE-HP-001 — Load valid title detail page', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto('/title/tmdb_movie_693134?country=US');
      await expect(Selectors.titleDetail.cheapestOptionHeading(page)).toBeVisible();
      consoleCapture.assertNoErrors();
    });

    test('TITLE-HP-002 — Navigate back from title detail page', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      // Simulating from search results
      await page.goto('/search?q=dune&country=US');
      await Selectors.search.titleCard(page).first().waitFor({ state: 'visible' });
      await Selectors.search.titleCard(page).first().click();
      await expect(page).toHaveURL(/title\/tmdb_movie_693134/);
      await Selectors.titleDetail.backButton(page).click();
      // Browser back button equivalent
      await expect(page).toHaveURL(/search\?q=dune&country=US/);
      consoleCapture.assertNoErrors();
    });

    test('TITLE-HP-003 — Verify free trial badge is displayed when available', async ({ page }) => {
      const consoleCapture = await attachConsoleCapture(page);
      await page.goto('/title/tmdb_movie_693134?country=US');
      await expect(Selectors.titleDetail.freeTrialBadge(page)).toBeVisible();
      consoleCapture.assertNoErrors();
    });
  });

  test.describe('Negative', () => {
    test('TITLE-NEG-001 — Invalid title ID returns 404/safe error', async ({ page }) => {
      await page.goto('/title/tmdb_invalid_id?country=US');
      // Look for the loading text to disappear and the title not found text OR check error handling
      await expect(page.locator('body')).toContainText(/Title not found/i);
    });
  });

  test.describe('API', () => {
    test('TITLE-API-001 — Invalid API query returns standard error', async ({ request }) => {
      const response = await request.get(`${API_URL}/api/search`);
      expect(response.status()).toBe(400);
      const data = await response.json();
      expect(data.error).toBe('Invalid query parameters');
    });

    test('TITLE-API-002 — 500 error from API handled gracefully', async ({ page }) => {
      await page.route('**/api/titles/**', route =>
        route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ error: 'Internal Server Error' }),
        })
      );
      await page.goto('/title/tmdb_movie_693134?country=US');
      await expect(page.locator('body')).toContainText(/Internal Server Error|failed to fetch|Title not found/i);
    });
  });
});

test.describe('NAVIGATION', () => {
  test('NAV-HP-001 — Ensure 404 page for unknown routes', async ({ page }) => {
    await page.goto('/unknown-route-123');
    await expect(page.locator('body')).toContainText(/404/i);
  });
});
