// AUTO-GENERATED by Universal QA Agent — Phase 2
// Do not edit manually. Re-run agent to regenerate.

import { Page } from '@playwright/test';

export const Selectors = {
  home: {
    searchInput: (page: Page) => page.getByPlaceholder(/search for a movie or show/i),
    countrySelect: (page: Page) => page.locator('select'), // CSS fallback for MVP select
    searchButton: (page: Page) => page.getByRole('button', { name: /search/i }),
  },
  search: {
    backLink: (page: Page) => page.getByRole('link', { name: /back to search/i }),
    titleCard: (page: Page) => page.locator('a[href^="/title/"]'), // Fallback for dynamic cards
    noResultsText: (page: Page) => page.getByText(/no results found/i),
  },
  titleDetail: {
    backButton: (page: Page) => page.getByRole('button', { name: /back/i }),
    cheapestOptionHeading: (page: Page) => page.getByText(/cheapest way to watch/i),
    freeTrialBadge: (page: Page) => page.getByText(/free trial available/i),
  },
  general: {
    loadingText: (page: Page) => page.getByText(/loading/i),
  }
};
